---
kind: pipeline
type: docker
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: hub.oepkgs.net/rfolabs/hardened-build-base:v1.17.13
  commands:
  - make DRONE_TAG=${DRONE_TAG}
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: publish
  image: hub.oepkgs.net/rfolabs/hardened-build-base:v1.17.13
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make DRONE_TAG=${DRONE_TAG} image-push
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - tag

- name: scan
  image: hub.oepkgs.net/rfolabs/hardened-build-base:v1.17.13
  commands:
  - make DRONE_TAG=${DRONE_TAG} image-scan
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

node:
  instance: agent-amd64

trigger:
  event:
    include:
    - tag

---
kind: pipeline
type: docker
name: linux-arm64

platform:
  os: linux
  arch: arm64

node:
  instance: agent-arm64

steps:
- name: build
  pull: always
  image: hub.oepkgs.net/rfolabs/hardened-build-base:v1.17.13
  failure: ignore
  commands:
  - make DRONE_TAG=${DRONE_TAG}
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: publish
  image: hub.oepkgs.net/rfolabs/hardened-build-base:v1.17.13
  failure: ignore
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make DRONE_TAG=${DRONE_TAG} image-push
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

trigger:
  event:
    include:
    - tag
---
kind: pipeline
type: docker
name: manifest
platform:
  os: linux
  arch: amd64
steps:
- name: push
  image: plugins/manifest
  settings:
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
    spec: manifest.tmpl
    ignore_missing: true
  when:
    event:
    - tag

depends_on:
- linux-amd64
- linux-arm64

node:
  instance: agent-amd64

trigger:
  event:
    include:
    - tag
...
